# (PART) Authors {-}

# Transparency and Openness Statements {#authors-top}

To enable readers to quickly and easily find open science disclosures, APA is requiring that authors include a subsection in their paper's Method section titled "Transparency and Openness". In this brief section, authors should disclose relevant details about seven TOP domains: availability of data, availability of code, availability of materials, citation to secondary data/code/materials (including citations of statistical software and packages), reporting standards, preregistration of study designs, and preregistration of analysis plans. The requirements for the information disclosed will depend on whether a journal has endorsed TOP level 1 or level 2. 

## Example TOP Statement

We report how we determined our sample size, all data exclusions, all manipulations, and all measures in the study, and we follow JARS [@kazak2018journal]. All data, analysis code, and research materials are available at [stable link to repository]. Data were analyzed using R, version 4.0.0 [@R] and the package lme4, version 1.1-27.1 [@lme4]. This study's design and its analysis were not pre-registered.
    
## Resources

* [APA TOP](https://www.apa.org/pubs/journals/resources/transparency-openness-promotion){target="_blank"}
* [OSF TOP](https://osf.io/9f6gx/){target="_blank"}
* [COS TOP](https://www.cos.io/initiatives/top-guidelines){target="_blank"}
* [APA Journal Reporting Standards](https://apastyle.apa.org/jars){target="_blank"}


# Registered Reports {#authors-registered-reports}

From [Center for Open Science](https://www.cos.io/initiatives/registered-reports){target="_blank"}:

> Registered Reports is a publishing format that emphasizes the importance of the research question and the quality of methodology by conducting peer review prior to data collection. High quality protocols are then provisionally accepted for publication if the authors follow through with the registered methodology.

> This format is designed to reward best practices in adhering to the hypothetico-deductive model of the scientific method. It eliminates a variety of questionable research practices, including low statistical power, selective reporting of results, and publication bias, while allowing complete flexibility to report serendipitous findings.

Benefits of the Registered Reports process from the perspective of authors include: receiving in-principle acceptance prior to investing scarce resources in running a study, getting peer input on study design prior to study onset when it is likely to be usefully incorporated, a chance to avoid resubmission of a paper at many journals prior to acceptance, and assurance that null results will receive equal treatment to positive results during consideration of a paper.

Authors have two options for Registered Reports. They may submit directly to a journal that offers the Registered Report submission type, or they may submit to the Peer Community In Registered Reports (PCI-RR). The PCI-RR is a journal independent peer reviewing service that manages the complete (stage 1 and stage 2) review of Registered Reports. After recommendation (i.e., acceptance) through the PCI-RR, authors are able to submit their work directly to participating journals. These journals either agree to accept relevant work outright (friendly journals) or after additional peer review (interested journals). 

## Resources

* [OSF RR protocol registration](https://osf.io/rr/){target="_blank"}
* [PCI Registered Reports](https://rr.peercommunityin.org/){target="_blank"}
* [Center for Open Science RR Resources](https://www.cos.io/initiatives/registered-reports){target="_blank"}

# Preregistration {#authors-prereg}

Preregistration is a process of planning a study and then making those plans transparently available in a read-only, time-stamped repository. A preregistration may contain study hypotheses, design, analysis, along with all related materials prepared in advance of the study (protocols, measures, code), depending on a researcher's goals. Studies involving the collection of new data may be preregistered, as can analysis of secondary data. A registration refers to the entry of a study in a publicly accessible study registry (see Appendix\ \@ref(registries)). A protocol refers to detailed plans outlining study methods, analysis plans and/or theoretical predictions.

When preparing your preregistration for inclusion in your manuscript, here are a few things to consider. First, make sure that the paper provides a link to the registry where it was preregistered. Self-hosted documents are not recommended. Second, the preregistration should be time-stamped and read-only. Finally, compare the study as reported in the final paper to the preregistered plan. If deviations from the plan have happened (which is typical), make sure that the deviations are transparently reported in the final paper so that readers can evaluate the consequences of the changes. Check to see if all planned analyses are reported in the paper, regardless of statistical significance of the outcome. Make sure that any additional exploratory analyses are transparently marked as such. It might be best to include those analyses in their own well-marked section following any confirmatory analyses. 

## Resources

* A template for preregistration of quantitative research in psychology: Report of the Joint Psychological Societies Preregistration Task Force [@bosnjak2021template]
* Preregistration of secondary data analysis: A template and tutorial [@van2021preregistration]
* Recommendations for increasing the transparency of analysis of preexisting data sets [@weston2019recommendations]
* OSF preregistration [forms and templates](https://osf.io/zab38/wiki/home/){target="_blank"}

# Open Materials {#authors-open-materials}

Provide research materials and description of procedures necessary to conduct an independent replication of the research.

If research materials are secondary, they should be cited rather than shared directly (see Section\ \@ref(authors-citation)). Include any information on how others can also obtain the materials.

If research materials are proprietary, include information on how to obtain them (if possible) and/or how to replicate them. For example, face images may not be shareable, but the procedure for generating the specific images used in a study can be included instead.

## Tips {#authors-materials-tips}

### Add a license

If you share your materials, including any figures in the manuscript, using an open license such as CC-BY, this makes reuse straightforward. See Appendix\ \@ref(licenses) for more details.

# Open Data {#authors-open-data}

Open data should include all variables, treatment conditions, and observations described in the manuscript, and provide a full account of the procedures used to collect, preprocess, clean, or generate the data. This data should allow for the reproduction of any plots, tables, or analyses reported in the manuscript.

If data are secondary, they should be cited rather than shared directly (see Section\ \@ref(authors-citation)). Include any information on how others can also obtain the data.

## Tips {#authors-data-tips}

### Save it in an accessible format

* Use tab-separated value (.tsv) or comma-separated value (.csv) files
* Use UTF-8 (or UTF-16) encoding to avoid problems in an international context (e.g., so characters like ü or é aren't mangled) 

Excel is less preferable because of the proprietary format and its tendency to mangle anything that resembles a date. SPSS and other proprietary formats are also not ideal, but data in a proprietary format is better than no data.

### Include a codebook

* <span class="beginner">Beginner</span>: include a text file with each column name and an explanation 
* <span class="intermediate">Intermediate</span>: You can include a data dictionary with further info like data type (string, numeric) or possible ranges/values [@buchanan2021getting]
* <span class="intermediate">Intermediate</span>: Use `faux::codebook()` to make a [machine-readable codebook](https://debruine.github.io/faux/articles/codebook.html){target="_blank"} in PsychDS format
* <span class="intermediate">Intermediate</span>: Use the R [codebook](https://rubenarslan.github.io/codebook/articles/codebook_tutorial.html){target="_blank"} to include a report with detailed metadata [@horstmann2020generating]


### Ethical sharing

* Check that you are not sharing any identifiable data (without clear consent), such as names, student ID numbers, postcodes, IP addresses, or uniquely identifying combinations of demographic variables.
* Add a license so others know how they can use the data. See Appendix\ \@ref(licenses) for more details. The most common licenses for data are:
    * CC-0: Waives all rights and releases work to public domain
    * CC-BY: By Attribution, which permits sharing and reuse of the material, for any purpose, as long as the original authors are credited
    * CC-BY-SA: By Attribution, with a Share-Alike clause which means that anyone sharing or modifying the original work must release it under the same license
* [Practical tips for ethical data sharing](https://doi.org/10.1177/2515245917747656){target="_blank"} (@meyer2018practical)

### Make it findable

* Use a persistent archive to host your data, like the [OSF](https://osf.io){target="_blank"}, [figshare](https://figshare.com/){target="_blank"}, or [zenodo](https://zenodo.org/){target="_blank"}. These platforms are free and can give your data a DOI.
* Include the citation info in a README
* Remember to make the data accessible for reviewers before submission. The OSF allows you to create a blinded [review-only link](https://help.osf.io/hc/en-us/articles/360019930333-Create-a-View-only-Link-for-a-Project){target="_blank"}.
* Make the data accessible to the public before publication.
* Make sure the paper contains the correct links to the data before publication.

## Resources

* [Guide to Social Science Data Preparation and Archiving](https://www.icpsr.umich.edu/web/pages/deposit/guide/index.html){target="_blank"}

# Open Code {#authors-open-code}

If research code is entirely secondary, it should be cited rather than shared directly (see Section\ \@ref(authors-citation)). However, this is likely to be rare, and research code that is modified in any way from the original should be both cited and shared. 

## Tips {#authors-code-tips}

### Make it reproducible

* Include all the external files (e.g., data files) needed to run it
* Use relative paths so that it can run on any computer
* Set a seed if your code uses simulations or random number generation

### Make it clear

* Include a README that explains how to run the code
* Assume that the audience has varying technical expertise and doesn't necessarily know the conventions of the language you're using
* Indicate which parts of your code produce any figure, table, or value in your manuscript
    * <span class="beginner">Beginner</span>: include comments in your code like `# produces Figure 3.1`
    * <span class="intermediate">Intermediate</span>: Use code the generate the text of the results section so you only have one thing to copy and paste into the manuscript
    * <span class="advanced">Advanced</span>: Use code to generate the entire manuscript (e.g., using the [papaja](http://frederikaust.com/papaja_man/){target="_blank"} package)

### Indicate software versions

* <span class="beginner">Beginner</span>: Include a text file with the info, e.g., devtools::session_info() in R, or requirements.txt in python
* <span class="intermediate">Intermediate</span>: Or use dependency management, like [renv](https://rstudio.github.io/renv/articles/renv.html){target="_blank"} or [packrat](https://rstudio.github.io/packrat/){target="_blank"} in R
* <span class="advanced">Advanced</span>: Or use containers like [Binder](https://mybinder.org/){target="_blank"}, [Docker](https://www.docker.com/){target="_blank"} or [CodeOcean](https://codeocean.com/){target="_blank"} for full reproducibility
  
### Confirm reproducibility

* <span class="beginner">Beginner</span>: Access your shared materials from a new computer and run the code
* <span class="intermediate">Intermediate</span>: Or ask a colleague to try running your code on their machine
* <span class="intermediate">Intermediate</span>: Or set up more formal code review [@vable2021code] in your group
* <span class="advanced">Advanced</span>: Or use a service like [CodeCheck](https://codecheck.org.uk/)

NB: If your code takes a very long time to run, such as when you have extremely large datasets or are running simulations, you can include smaller test datasets or run a smaller number of replications and include code at the top of the script to toggle real and test data or low and high numbers of reps.

### Share and license

* Add a license so others know how they can use and modify the code. See Appendix\ \@ref(licenses) for more details.
* Make your code findable using the same tips from Section\ \@ref(make-it-findable) 
* [GitHub](https://github.com/){target="_blank"} is a common place to share code, but doesn't create a DOI, so if you use github, consider archiving a snapshot of your repository on [zenodo](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content){target="_blank"}.

# Citation {#authors-citation}

Papers using secondary (i.e., from other sources) data, materials, or analysis code must cite those artifacts in the TOP statement. All citations should be to persistent/stable identifiers (DOIs) whenever possible. If creators of data, materials, or code have provided a preferred citation, that source should be cited, along with a way for readers to access the shared material (e.g., on a website or in a repository).

Note, secondary analysis code includes software packages (e.g., R packages), as well as custom analysis code (e.g., code that you, as authors, did not write, but that someone else prepared for a specific use). The majority of papers will have some research software to cite, and it is often overlooked or forgotten. Remember to include version numbers with any software packages. If the amount of information is extensive, a supplementary table can be included with the relevant version and citation information.

You might be tempted to provide citations in other parts of the Method or Results sections (e.g., Analysis Plan for secondary code or Materials for secondary materials), but for completeness, such information should be relocated to the TOP statement. Citations in the TOP statement should be, where possible, to the source of the material, data, software or code, rather than to papers that only describe the material, but do not provide access to it. Such descriptive citations can be included in the main text of the paper, if desired.
When data, materials, or code are primary (i.e., created by your author team and published alongside your article), remember to openly license those artifacts and see the Open Data, Open Materials, and Open Code sections for more guidance. When data, materials, or code are secondary, make sure to cite those artifacts as described here, and avoid sharing copies those artifacts in full to avoid issues with copyright (unless they are permissively licensed to allow such sharing). 


# Authorship {#authors-authorship}

Specifying each author's roles allows for transparent attribution of credit, especially when papers have many authors. The Tenzing [r package](https://marton-balazs-kovacs.github.io/tenzing/){target="_blank"} or [web app](https://tenzing.club/){target="_blank"} app can help you manage this.

You may include a statement of author contributions whether or not the journal requires CRediT statements. Simply include the statement of contributions in the Author Note unless other directions are provided in a journal’s submission guidelines. See the resources section below for tips on preparing CRediT statements. 

## Roles

* Conceptualization: Ideas; formulation or evolution of overarching research goals and aims.
* Data curation: Management activities to annotate (produce metadata), scrub data and maintain research data (including software code, where it is necessary for interpreting the data itself) for initial use and later re-use.
* Formal analysis: Application of statistical, mathematical, computational, or other formal techniques to analyse or synthesize study data.
* Funding acquisition: Acquisition of the financial support for the project leading to this publication.
* Investigation: Conducting a research and investigation process, specifically performing the experiments, or data/evidence collection.
* Methodology: Development or design of methodology; creation of models.
* Project administration: Management and coordination responsibility for the research activity planning and execution.
* Resources: Provision of study materials, reagents, materials, patients, laboratory samples, animals, instrumentation, computing resources, or other analysis tools.
* Software: Programming, software development; designing computer programs; implementation of the computer code and supporting algorithms; testing of existing code components.
* Supervision: Oversight and leadership responsibility for the research activity planning and execution, including mentorship external to the core team.
* Validation: Verification, whether as a part of the activity or separate, of the overall replication/reproducibility of results/experiments and other research outputs.
* Visualization: Preparation, creation and/or presentation of the published work, specifically visualization/data presentation.
* Writing - original draft: Preparation, creation and/or presentation of the published work, specifically writing the initial draft (including substantive translation).
* Writing - review & editing: Preparation, creation and/or presentation of the published work by those from the original research group, specifically critical review, commentary or revision -- including pre- or post-publication stages.

## Resources

* Tenzing [r package](https://marton-balazs-kovacs.github.io/tenzing/){target="_blank"} and [web app](https://tenzing.club/){target="_blank"}
* [Casrai CRediT](https://casrai.org/credit/){target="_blank"}
* Holcombe's accessible [intro to CRediT, using tenzing](https://alexholcombe.medium.com/announcing-tenzing-ceca6789d88c){target="_blank"}


# Preprints and Postprints {#authors-preprints}

Preprints are author copies of manuscripts prior to acceptance by a journal (preprints are also called "submitted" manuscripts). Postprints are author copies of manuscripts after acceptance for publication by a journal (postprints are also called "accepted" manuscripts). Sharing preprints and postprints increases access to research. Papers are indexed by Google Scholar and Europe PMC, increasing discoverability. Preprint authors also have the chance to receive feedback on their work, improving its quality prior to publication. As of August 2022, all APA core titles allow posting of preprints and postprints without embargo.

Most journals in psychology allow the submission of preprints (submitted manuscripts) to disciplinary repositories like PsyArXiv without embargo or restriction, and a growing number also allow submission of postprints (accepted manuscripts) without any embargo. By contrast, the journal-typeset version of an article is often referred to as the “published version,” and this version is usually subject to more restrictions on sharing. Authors can check [Sherpa Romeo](https://v2.sherpa.ac.uk/romeo/) to verify the policies of the journal to which they are submitting or have been accepted. 
